package org.example.fitwinkmp.core.localization

data class AppStrings(
    // Bottom nav
    val navNutricion: String,
    val navEntreno: String,
    val navStats: String,
    val navPerfil: String,

    // Food screen
    val foodRegistroDiario: String,
    val foodHoy: String,
    val foodTitulo1: String,   // "ALIMENTA TU" / "FUEL YOUR"
    val foodTitulo2: String,   // "MOTOR" / "ENGINE"
    val foodCaloriasRest: String,
    val foodObjetivoKcal: String, // "OBJETIVO: X KCAL" prefix
    val foodProteinas: String,
    val foodCarbos: String,
    val foodGrasas: String,
    val foodDesayuno: String,
    val foodAlmuerzo: String,
    val foodCena: String,
    val foodSnacks: String,
    val foodRegistrado: String,
    val foodTocaParaRegistrar: String, // prefix, meal name appended
    val foodGuardar: String,
    val foodCancelar: String,
    val foodNombreAlimento: String,
    val foodCantidad: String,
    val foodUnidad: String,
    val foodRegistrar: String, // "REGISTRAR" / "LOG" prefix in dialog title
    val foodEliminar: String,
    val foodEditar: String,

    // Training screen
    val trainingTitle: String,
    val trainingPlanHoy: String,
    val trainingDiaDescanso: String,
    val trainingCrearRutina: String,
    val trainingSesionActiva: String,
    val trainingAplastaReps: String,
    val trainingObjetivo: String, // "OBJETIVO:" prefix
    val trainingSerie: String,
    val trainingTodasSeries: String,
    val trainingIniciarSesion: String,
    val trainingFinalizarSesion: String,
    val trainingNuevaRutina: String,
    val trainingEliminarRutina: String,
    val trainingSeleccionarRutina: String,
    val trainingAnyadirEjercicio: String,
    val trainingNombreEjercicio: String,
    val trainingEjemploEjercicio: String,
    val trainingSeries: String,
    val trainingDescansoSeg: String,
    val trainingRepsMin: String,
    val trainingRepsMax: String,
    val trainingGuardarRutina: String,
    val trainingNombreRutina: String,
    val trainingSinEjercicios: String,
    val trainingAnadir: String,
    val trainingCancelar: String,
    val trainingDescanso: String, // "REST" in reps label
    val trainingRegistrar: String, // "LOG" button
    val trainingEditarRutina: String,

    // Profile
    val profilePesoActual: String,
    val profileAltura: String,
    val profileImc: String,
    val profileActividad: String,
    val profileObjetivoNutricional: String,
    val profileMiCuenta: String,
    val profileEditarPerfil: String,
    val profileInfoCuenta: String,
    val profileCerrarSesion: String,
    val profileActualizado: String,
    val profileReintentar: String,
    val profileDesdeRegistro: String,
    val profileGenerarObjetivo: String,

    // Edit profile dialog
    val editPerfilTitulo1: String,
    val editPerfilTitulo2: String,
    val editPerfilCancelar: String,
    val editPerfilDatosPersonales: String,
    val editPerfilDatosFisicos: String,
    val editPerfilNombre: String,
    val editPerfilApellidos: String,
    val editPerfilEmail: String,
    val editPerfilPeso: String,
    val editPerfilAltura: String,
    val editPerfilGenero: String,
    val editPerfilNivelActividad: String,
    val editPerfilObjetivo: String,
    val editPerfilGuardar: String,

    // Settings
    val settingsTitulo: String,
    val settingsIdioma: String,
    val settingsEspanyol: String,
    val settingsEspanyolSub: String,
    val settingsIngles: String,
    val settingsInglesSub: String,
    val settingsInfoText: String,
    val settingsVersion: String,

    // Common
    val commonProximamente: String,
    val commonEstadisticas: String,
    val commonAjustes: String,
    val commonLoading: String,

    // Stats Screen
    val statsTabPerformance: String,
    val statsTabPhysique: String,
    val statsRegistraProgresoHoy: String,
    val statsSinDatosHoy: String,
    val statsProgresoRegistrado: String,
    val statsEditar: String,

    // Physique Tab
    val statsBody: String,
    val statsComposition: String,
    val statsSinMedicionesAun: String,
    val statsPulsaBannerRegistrar: String,
    val statsPesoActual: String,
    val statsMasaMagra: String,
    val statsTendencia: String,
    val statsMedidasMusculares: String,
    val statsSinMedidasMusculares: String,
    val statsTendenciasUltimoMes: String,
    val statsNecesitas2Mediciones: String,
    val statsEsteMes: String,
    val statsEvolucionPeso: String,
    val statsVerGraficaCompleta: String,

    // Performance Tab
    val statsKinetic: String,
    val statsVelocity: String,
    val statsAnalisisRendimiento: String,
    val statsLogroPrincipal: String,
    val statsTonelajeLevantado: String,
    val statsSesiones7Dias: String,
    val statsDuracionMedia: String,
    val statsDiasRacha: String,
    val statsIntensidad: String,
    val statsRecuperacion: String,
    val statsRecordsPersonales: String,
    val statsMejorMarca: String,
    val stats1RmEstimados: String,
    val statsEpleyFormula: String,
    val statsAdherenciaNutricional: String,
    val statsSinDatosNutricionales: String,
    val statsProteinaPorKg: String,

    // Chart Sheet
    val statsProgreso: String,
    val statsResumenPeriodo: String,
    val statsInicio: String,
    val statsActual: String,
    val statsCambio: String,
    val statsMin: String,
    val statsMax: String,
    val statsMedia: String,
    val statsMedicionesRegistradas: String,
    val statsHaSubido: String,
    val statsHaMejorado: String,
    val statsHaBajado: String,
    val statsSinCambios: String,

    // CheckIn Sheet
    val statsCheckIn: String,
    val statsDiario: String,
    val statsActualizar: String,
    val statsMedicionDeHoy: String,
    val statsRegistraProgreso: String,
    val statsYaRegistrasteHoy: String,
    val statsRepetirUltima: String,
    val statsPesoInput: String,
    val statsGrasaInput: String,
    val statsOcultarMedidas: String,
    val statsAnadirMedidas: String,
    val statsMedidasMuscularesCm: String,
    val statsCancelar: String,
    val statsGuardar: String,

    // Chart Metrica
    val statsMetricaPeso: String,
    val statsMetricaGrasa: String,
    val statsMetricaMasaMagra: String,
    val statsMetricaPecho: String,
    val statsMetricaEspalda: String,
    val statsMetricaHombro: String,
    val statsMetricaBrazo: String,
    val statsMetricaMuslo: String,
    val statsMetricaCintura: String,

    // Auth Screens
    val authWelcomeBack: String,
    val authJoinElite: String,
    val authSubtitle: String,
    val authSignIn: String,
    val authSignInDesc: String,
    val authCreateAccount: String,
    val authCreateAccountDesc: String,
    val authEmail: String,
    val authPassword: String,
    val authForgotPassword: String,
    val authEnterArena: String,
    val authNewToSquad: String,
    val authAlreadySquad: String,
    val authLogIn: String,
    val authCopyright: String,
    val authName: String,
    val authSurname: String,
    val authWeight: String,
    val authHeight: String,
    val authDob: String,
    val authGender: String,
    val authActivityLevel: String,
    val authObjective: String,
    val authTerms: String,
    val authInitialize: String
)
