package org.example.fitwinkmp.core.localization

val stringsEn = AppStrings(
    // Bottom nav
    navNutricion = "Nutrition",
    navEntreno = "Training",
    navStats = "Stats",
    navPerfil = "Profile",

    // Food
    foodRegistroDiario = "DAILY LOG",
    foodHoy = "TODAY",
    foodTitulo1 = "FUEL YOUR",
    foodTitulo2 = "ENGINE",
    foodCaloriasRest = "CALORIES LEFT",
    foodObjetivoKcal = "GOAL:",
    foodProteinas = "PROTEIN",
    foodCarbos = "CARBS",
    foodGrasas = "FATS",
    foodDesayuno = "BREAKFAST",
    foodAlmuerzo = "LUNCH",
    foodCena = "DINNER",
    foodSnacks = "SNACKS",
    foodRegistrado = "Logged",
    foodTocaParaRegistrar = "TAP TO LOG YOUR",
    foodGuardar = "SAVE",
    foodCancelar = "CANCEL",
    foodNombreAlimento = "Food Name",
    foodCantidad = "Qty",
    foodUnidad = "Unit",
    foodRegistrar = "LOG",
    foodEliminar = "Delete",
    foodEditar = "Edit",

    // Training
    trainingTitle = "TRAINING",
    trainingPlanHoy = "TODAY'S PLAN",
    trainingDiaDescanso = "REST DAY OR NO ROUTINE",
    trainingCrearRutina = "BUILD ROUTINE",
    trainingSesionActiva = "SESSION ACTIVE",
    trainingAplastaReps = "CRUSH IT",
    trainingObjetivo = "GOAL:",
    trainingSerie = "SET",
    trainingTodasSeries = "ALL SETS COMPLETED",
    trainingIniciarSesion = "START WORKOUT",
    trainingFinalizarSesion = "FINISH WORKOUT",
    trainingNuevaRutina = "New Routine",
    trainingEliminarRutina = "Delete Current Routine",
    trainingSeleccionarRutina = "Select Routine",
    trainingAnyadirEjercicio = "ADD EXERCISE",
    trainingNombreEjercicio = "Exercise Name",
    trainingEjemploEjercicio = "e.g. Bench Press, Squats...",
    trainingSeries = "Sets",
    trainingDescansoSeg = "Rest (s)",
    trainingRepsMin = "Min Reps",
    trainingRepsMax = "Max Reps",
    trainingGuardarRutina = "SAVE ROUTINE",
    trainingNombreRutina = "Routine Name",
    trainingSinEjercicios = "No exercises added for this day",
    trainingAnadir = "ADD",
    trainingCancelar = "CANCEL",
    trainingDescanso = "REST",
    trainingRegistrar = "LOG",
    trainingEditarRutina = "Edit routine",

    // Profile
    profilePesoActual = "CURRENT WEIGHT",
    profileAltura = "HEIGHT",
    profileImc = "BMI",
    profileActividad = "ACTIVITY",
    profileObjetivoNutricional = "NUTRITIONAL GOAL",
    profileMiCuenta = "MY ACCOUNT",
    profileEditarPerfil = "Edit Profile",
    profileInfoCuenta = "Account Information",
    profileCerrarSesion = "LOG OUT",
    profileActualizado = "✓ Profile updated",
    profileReintentar = "RETRY",
    profileDesdeRegistro = "kg from baseline",
    profileGenerarObjetivo = "Generate goal",

    // Edit profile dialog
    editPerfilTitulo1 = "EDIT",
    editPerfilTitulo2 = "PROFILE",
    editPerfilCancelar = "CANCEL",
    editPerfilDatosPersonales = "PERSONAL DATA",
    editPerfilDatosFisicos = "PHYSICAL DATA",
    editPerfilNombre = "Name",
    editPerfilApellidos = "Last Name",
    editPerfilEmail = "Email",
    editPerfilPeso = "Weight (kg)",
    editPerfilAltura = "Height (cm)",
    editPerfilGenero = "GENDER",
    editPerfilNivelActividad = "ACTIVITY LEVEL",
    editPerfilObjetivo = "GOAL",
    editPerfilGuardar = "SAVE CHANGES",

    // Settings
    settingsTitulo = "SETTINGS",
    settingsIdioma = "LANGUAGE",
    settingsEspanyol = "Español",
    settingsEspanyolSub = "Idioma de la aplicación",
    settingsIngles = "English",
    settingsInglesSub = "Application language",
    settingsInfoText = "More configuration options coming soon.",
    settingsVersion = "FIT-WIN v1.0.0",

    // Common
    commonProximamente = "COMING SOON",
    commonEstadisticas = "STATISTICS",
    commonAjustes = "Settings",
    commonLoading = "Loading..."
)
