package org.example.fitwinkmp.core.localization

val stringsEs = AppStrings(
    // Bottom nav
    navNutricion = "Nutrición",
    navEntreno = "Entreno",
    navStats = "Stats",
    navPerfil = "Perfil",

    // Food
    foodRegistroDiario = "REGISTRO DIARIO",
    foodHoy = "HOY",
    foodTitulo1 = "ALIMENTA TU",
    foodTitulo2 = "MOTOR",
    foodCaloriasRest = "CALORÍAS REST.",
    foodObjetivoKcal = "OBJETIVO:",
    foodProteinas = "PROTEÍNAS",
    foodCarbos = "CARBOS",
    foodGrasas = "GRASAS",
    foodDesayuno = "DESAYUNO",
    foodAlmuerzo = "ALMUERZO",
    foodCena = "CENA",
    foodSnacks = "SNACKS",
    foodRegistrado = "Registrado",
    foodTocaParaRegistrar = "TOCA PARA REGISTRAR",
    foodGuardar = "GUARDAR",
    foodCancelar = "CANCELAR",
    foodNombreAlimento = "Nombre del alimento",
    foodCantidad = "Cant.",
    foodUnidad = "Unidad",
    foodRegistrar = "REGISTRAR",
    foodEliminar = "Eliminar",
    foodEditar = "Editar",

    // Training
    trainingTitle = "ENTRENO",
    trainingPlanHoy = "PLAN DE HOY",
    trainingDiaDescanso = "DÍA DE DESCANSO O SIN RUTINA",
    trainingCrearRutina = "CREAR RUTINA",
    trainingSesionActiva = "SESIÓN ACTIVA",
    trainingAplastaReps = "¡A POR ELLO!",
    trainingObjetivo = "OBJETIVO:",
    trainingSerie = "SERIE",
    trainingTodasSeries = "TODAS LAS SERIES COMPLETADAS",
    trainingIniciarSesion = "INICIAR SESIÓN",
    trainingFinalizarSesion = "FINALIZAR SESIÓN",
    trainingNuevaRutina = "Nueva rutina",
    trainingEliminarRutina = "Eliminar rutina actual",
    trainingSeleccionarRutina = "Seleccionar rutina",
    trainingAnyadirEjercicio = "AÑADIR EJERCICIO",
    trainingNombreEjercicio = "Nombre del ejercicio",
    trainingEjemploEjercicio = "Ej. Press Banca, Sentadilla...",
    trainingSeries = "Series",
    trainingDescansoSeg = "Descanso (s)",
    trainingRepsMin = "Reps mín.",
    trainingRepsMax = "Reps máx.",
    trainingGuardarRutina = "GUARDAR RUTINA",
    trainingNombreRutina = "Nombre de la rutina",
    trainingSinEjercicios = "Sin ejercicios para este día",
    trainingAnadir = "AÑADIR",
    trainingCancelar = "CANCELAR",
    trainingDescanso = "DESCANSO",
    trainingRegistrar = "REGISTRAR",
    trainingEditarRutina = "Editar rutina",
    dayLunes = "LUNES",
    dayMartes = "MARTES",
    dayMiercoles = "MIÉRCOLES",
    dayJueves = "JUEVES",
    dayViernes = "VIERNES",
    daySabado = "SÁBADO",
    dayDomingo = "DOMINGO",
    dayInicialLunes = "L",
    dayInicialMartes = "M",
    dayInicialMiercoles = "X",
    dayInicialJueves = "J",
    dayInicialViernes = "V",
    dayInicialSabado = "S",
    dayInicialDomingo = "D",

    // Profile
    profilePesoActual = "PESO ACTUAL",
    profileAltura = "ALTURA",
    profileImc = "IMC",
    profileActividad = "ACTIVIDAD",
    profileObjetivoNutricional = "OBJETIVO NUTRICIONAL",
    profileMiCuenta = "MI CUENTA",
    profileEditarPerfil = "Editar perfil",
    profileInfoCuenta = "Información de la cuenta",
    profileCerrarSesion = "CERRAR SESIÓN",
    profileActualizado = "✓ Perfil actualizado",
    profileReintentar = "REINTENTAR",
    profileDesdeRegistro = "kg desde el registro",
    profileGenerarObjetivo = "Generar objetivo",

    // Edit profile dialog
    editPerfilTitulo1 = "EDITAR",
    editPerfilTitulo2 = "PERFIL",
    editPerfilCancelar = "CANCELAR",
    editPerfilDatosPersonales = "DATOS PERSONALES",
    editPerfilDatosFisicos = "DATOS FÍSICOS",
    editPerfilNombre = "Nombre",
    editPerfilApellidos = "Apellidos",
    editPerfilEmail = "Email",
    editPerfilPeso = "Peso (kg)",
    editPerfilAltura = "Altura (cm)",
    editPerfilGenero = "GÉNERO",
    editPerfilNivelActividad = "NIVEL DE ACTIVIDAD",
    editPerfilObjetivo = "OBJETIVO",
    editPerfilGuardar = "GUARDAR CAMBIOS",

    // Settings
    settingsTitulo = "AJUSTES",
    settingsIdioma = "IDIOMA",
    settingsEspanyol = "Español",
    settingsEspanyolSub = "Idioma actual de la aplicación",
    settingsIngles = "English",
    settingsInglesSub = "Application language",
    settingsInfoText = "Más opciones de configuración próximamente.",
    settingsVersion = "FIT-WIN v1.0.0",

    // Common
    commonProximamente = "PRÓXIMAMENTE",
    commonEstadisticas = "ESTADÍSTICAS",
    commonAjustes = "Ajustes",
    commonLoading = "Cargando...",

    // Stats Screen
    statsTabPerformance = "RENDIMIENTO",
    statsTabPhysique = "MEDIDAS",
    statsRegistraProgresoHoy = "REGISTRA TU PROGRESO DE HOY",
    statsSinDatosHoy = "Sin datos de hoy aún",
    statsProgresoRegistrado = "✓ Progreso de hoy registrado — toca para editar",
    statsEditar = "EDITAR",

    // Physique Tab
    statsBody = "COMPOSICIÓN",
    statsComposition = "CORPORAL",
    statsSinMedicionesAun = "SIN MEDICIONES AÚN",
    statsPulsaBannerRegistrar = "Pulsa el banner de arriba para registrar\ntu primera medición corporal",
    statsPesoActual = "PESO ACTUAL",
    statsMasaMagra = "MASA MAGRA",
    statsTendencia = "TENDENCIA",
    statsMedidasMusculares = "MEDIDAS MUSCULARES",
    statsSinMedidasMusculares = "Sin medidas musculares registradas",
    statsTendenciasUltimoMes = "TENDENCIAS · ÚLTIMO MES",
    statsNecesitas2Mediciones = "Necesitas al menos 2 mediciones para ver tendencias",
    statsEsteMes = "este mes",
    statsEvolucionPeso = "EVOLUCIÓN DE PESO",
    statsVerGraficaCompleta = "VER GRÁFICA COMPLETA",

    // Performance Tab
    statsKinetic = "CINÉTICA",
    statsVelocity = "VELOCIDAD",
    statsAnalisisRendimiento = "Análisis de rendimiento · último mes",
    statsLogroPrincipal = "LOGRO PRINCIPAL",
    statsTonelajeLevantado = "TONELAJE LEVANTADO · ÚLTIMO MES",
    statsSesiones7Dias = "SESIONES\n7 DÍAS",
    statsDuracionMedia = "DURACIÓN\nMEDIA",
    statsDiasRacha = "DÍAS DE\nRACHA",
    statsIntensidad = "INTENSIDAD",
    statsRecuperacion = "RECUPERACIÓN",
    statsRecordsPersonales = "RÉCORDS PERSONALES",
    statsMejorMarca = "MEJOR MARCA",
    stats1RmEstimados = "1RM ESTIMADOS",
    statsEpleyFormula = "Calculado con la fórmula de Epley (peso × (1 + reps/30))",
    statsAdherenciaNutricional = "ADHERENCIA NUTRICIONAL · HOY",
    statsSinDatosNutricionales = "Sin datos nutricionales para hoy",
    statsProteinaPorKg = "PROTEÍNA / KG CORPORAL",

    // Chart Sheet
    statsProgreso = "PROGRESO",
    statsResumenPeriodo = "RESUMEN DEL PERÍODO",
    statsInicio = "INICIO",
    statsActual = "ACTUAL",
    statsCambio = "CAMBIO",
    statsMin = "MIN",
    statsMax = "MAX",
    statsMedia = "MEDIA",
    statsMedicionesRegistradas = "mediciones registradas",
    statsHaSubido = "Ha subido en este período",
    statsHaMejorado = "Ha mejorado en este período",
    statsHaBajado = "Ha bajado en este período",
    statsSinCambios = "Sin cambios en este período",

    // CheckIn Sheet
    statsCheckIn = "CHECK-IN",
    statsDiario = "DIARIO",
    statsActualizar = "ACTUALIZAR",
    statsMedicionDeHoy = "MEDICIÓN DE HOY",
    statsRegistraProgreso = "Registra tu progreso de hoy",
    statsYaRegistrasteHoy = "Ya registraste hoy — actualizando tu medición existente",
    statsRepetirUltima = "REPETIR ÚLTIMA MEDICIÓN",
    statsPesoInput = "PESO (kg)*",
    statsGrasaInput = "% GRASA CORPORAL (opcional)",
    statsOcultarMedidas = "▲ OCULTAR MEDIDAS DETALLADAS",
    statsAnadirMedidas = "▼ AÑADIR MEDIDAS DETALLADAS",
    statsMedidasMuscularesCm = "MEDIDAS MUSCULARES (cm)",
    statsCancelar = "CANCELAR",
    statsGuardar = "GUARDAR",

    // Chart Metrica
    statsMetricaPeso = "Peso",
    statsMetricaGrasa = "% Grasa",
    statsMetricaMasaMagra = "Masa Magra",
    statsMetricaPecho = "Pecho",
    statsMetricaEspalda = "Espalda",
    statsMetricaHombro = "Hombro",
    statsMetricaBrazo = "Brazo",
    statsMetricaMuslo = "Muslo",
    statsMetricaCintura = "Cintura",

    // Auth Screens
    authWelcomeBack = "BIENVENIDO DE NUEVO",
    authJoinElite = "ÚNETE A LA ÉLITE",
    authSubtitle = "Ingeniería de alto rendimiento\npara tu evolución física.",
    authSignIn = "Iniciar Sesión",
    authSignInDesc = "Introduce tus credenciales para continuar.",
    authCreateAccount = "Crear Cuenta",
    authCreateAccountDesc = "Introduce tus datos para empezar.",
    authEmail = "CORREO ELECTRÓNICO",
    authPassword = "CONTRASEÑA",
    authForgotPassword = "¿Olvidaste tu contraseña?",
    authEnterArena = "ENTRAR A LA ARENA",
    authNewToSquad = "¿Nuevo en el equipo? ",
    authAlreadySquad = "¿Ya eres parte del equipo? ",
    authLogIn = "Inicia Sesión",
    authCopyright = "© 2024 FIT-WIN PERFORMANCE TECHNOLOGIES",
    authName = "NOMBRE",
    authSurname = "APELLIDOS",
    authWeight = "PESO (KG)",
    authHeight = "ALTURA (CM)",
    authDob = "FECHA NAC. (AAAA-MM-DD)",
    authGender = "GÉNERO",
    authActivityLevel = "NIVEL DE ACTIVIDAD",
    authObjective = "OBJETIVO",
    authTerms = "Acepto los Términos de Servicio y la Política de Privacidad",
    authInitialize = "INICIALIZAR ENTRENAMIENTO"
)
