package org.example.fitwinkmp.core.localization

val stringsEn = AppStrings(
    // Bottom nav
    navNutricion = "Nutrition",
    navEntreno = "Training",
    navStats = "Stats",
    navPerfil = "Profile",

    // Food
    foodRegistroDiario = "DAILY LOG",
    foodHoy = "TODAY",
    foodTitulo1 = "FUEL YOUR",
    foodTitulo2 = "ENGINE",
    foodCaloriasRest = "CALORIES LEFT",
    foodObjetivoKcal = "GOAL:",
    foodProteinas = "PROTEIN",
    foodCarbos = "CARBS",
    foodGrasas = "FATS",
    foodDesayuno = "BREAKFAST",
    foodAlmuerzo = "LUNCH",
    foodCena = "DINNER",
    foodSnacks = "SNACKS",
    foodRegistrado = "Logged",
    foodTocaParaRegistrar = "TAP TO LOG YOUR",
    foodGuardar = "SAVE",
    foodCancelar = "CANCEL",
    foodNombreAlimento = "Food Name",
    foodCantidad = "Qty",
    foodUnidad = "Unit",
    foodRegistrar = "LOG",
    foodEliminar = "Delete",
    foodEditar = "Edit",

    // Training
    trainingTitle = "TRAINING",
    trainingPlanHoy = "TODAY'S PLAN",
    trainingDiaDescanso = "REST DAY OR NO ROUTINE",
    trainingCrearRutina = "BUILD ROUTINE",
    trainingSesionActiva = "SESSION ACTIVE",
    trainingAplastaReps = "CRUSH IT",
    trainingObjetivo = "GOAL:",
    trainingSerie = "SET",
    trainingTodasSeries = "ALL SETS COMPLETED",
    trainingIniciarSesion = "START WORKOUT",
    trainingFinalizarSesion = "FINISH WORKOUT",
    trainingNuevaRutina = "New Routine",
    trainingEliminarRutina = "Delete Current Routine",
    trainingSeleccionarRutina = "Select Routine",
    trainingAnyadirEjercicio = "ADD EXERCISE",
    trainingNombreEjercicio = "Exercise Name",
    trainingEjemploEjercicio = "e.g. Bench Press, Squats...",
    trainingSeries = "Sets",
    trainingDescansoSeg = "Rest (s)",
    trainingRepsMin = "Min Reps",
    trainingRepsMax = "Max Reps",
    trainingGuardarRutina = "SAVE ROUTINE",
    trainingNombreRutina = "Routine Name",
    trainingSinEjercicios = "No exercises added for this day",
    trainingAnadir = "ADD",
    trainingCancelar = "CANCEL",
    trainingDescanso = "REST",
    trainingRegistrar = "LOG",
    trainingEditarRutina = "Edit routine",

    // Profile
    profilePesoActual = "CURRENT WEIGHT",
    profileAltura = "HEIGHT",
    profileImc = "BMI",
    profileActividad = "ACTIVITY",
    profileObjetivoNutricional = "NUTRITIONAL GOAL",
    profileMiCuenta = "MY ACCOUNT",
    profileEditarPerfil = "Edit Profile",
    profileInfoCuenta = "Account Information",
    profileCerrarSesion = "LOG OUT",
    profileActualizado = "✓ Profile updated",
    profileReintentar = "RETRY",
    profileDesdeRegistro = "kg from baseline",
    profileGenerarObjetivo = "Generate goal",

    // Edit profile dialog
    editPerfilTitulo1 = "EDIT",
    editPerfilTitulo2 = "PROFILE",
    editPerfilCancelar = "CANCEL",
    editPerfilDatosPersonales = "PERSONAL DATA",
    editPerfilDatosFisicos = "PHYSICAL DATA",
    editPerfilNombre = "Name",
    editPerfilApellidos = "Last Name",
    editPerfilEmail = "Email",
    editPerfilPeso = "Weight (kg)",
    editPerfilAltura = "Height (cm)",
    editPerfilGenero = "GENDER",
    editPerfilNivelActividad = "ACTIVITY LEVEL",
    editPerfilObjetivo = "GOAL",
    editPerfilGuardar = "SAVE CHANGES",

    // Settings
    settingsTitulo = "SETTINGS",
    settingsIdioma = "LANGUAGE",
    settingsEspanyol = "Español",
    settingsEspanyolSub = "Idioma de la aplicación",
    settingsIngles = "English",
    settingsInglesSub = "Application language",
    settingsInfoText = "More configuration options coming soon.",
    settingsVersion = "FIT-WIN v1.0.0",

    // Common
    commonProximamente = "COMING SOON",
    commonEstadisticas = "STATISTICS",
    commonAjustes = "Settings",
    commonLoading = "Loading...",

    // Stats Screen
    statsTabPerformance = "PERFORMANCE",
    statsTabPhysique = "PHYSIQUE",
    statsRegistraProgresoHoy = "LOG TODAY'S PROGRESS",
    statsSinDatosHoy = "No data for today yet",
    statsProgresoRegistrado = "✓ Today's progress logged — tap to edit",
    statsEditar = "EDIT",

    // Physique Tab
    statsBody = "BODY",
    statsComposition = "COMPOSITION",
    statsSinMedicionesAun = "NO MEASUREMENTS YET",
    statsPulsaBannerRegistrar = "Tap the banner above to log\nyour first body measurement",
    statsPesoActual = "CURRENT WEIGHT",
    statsMasaMagra = "LEAN MASS",
    statsTendencia = "TREND",
    statsMedidasMusculares = "MUSCLE MEASUREMENTS",
    statsSinMedidasMusculares = "No muscle measurements logged",
    statsTendenciasUltimoMes = "TRENDS · LAST MONTH",
    statsNecesitas2Mediciones = "You need at least 2 measurements to see trends",
    statsEsteMes = "this month",
    statsEvolucionPeso = "WEIGHT EVOLUTION",
    statsVerGraficaCompleta = "VIEW FULL CHART",

    // Performance Tab
    statsKinetic = "KINETIC",
    statsVelocity = "VELOCITY",
    statsAnalisisRendimiento = "Performance analysis · last month",
    statsLogroPrincipal = "MAIN ACHIEVEMENT",
    statsTonelajeLevantado = "LIFTED TONNAGE · LAST MONTH",
    statsSesiones7Dias = "SESSIONS\n7 DAYS",
    statsDuracionMedia = "AVG\nDURATION",
    statsDiasRacha = "STREAK\nDAYS",
    statsIntensidad = "INTENSITY",
    statsRecuperacion = "RECOVERY",
    statsRecordsPersonales = "PERSONAL BESTS",
    statsMejorMarca = "BEST MARK",
    stats1RmEstimados = "ESTIMATED 1RM",
    statsEpleyFormula = "Calculated with Epley's formula (weight × (1 + reps/30))",
    statsAdherenciaNutricional = "NUTRITIONAL ADHERENCE · TODAY",
    statsSinDatosNutricionales = "No nutritional data for today",
    statsProteinaPorKg = "PROTEIN / BODY KG",

    // Chart Sheet
    statsProgreso = "PROGRESS",
    statsResumenPeriodo = "PERIOD SUMMARY",
    statsInicio = "START",
    statsActual = "CURRENT",
    statsCambio = "CHANGE",
    statsMin = "MIN",
    statsMax = "MAX",
    statsMedia = "AVG",
    statsMedicionesRegistradas = "measurements logged",
    statsHaSubido = "Went up this period",
    statsHaMejorado = "Improved this period",
    statsHaBajado = "Went down this period",
    statsSinCambios = "No changes this period",

    // CheckIn Sheet
    statsCheckIn = "CHECK-IN",
    statsDiario = "DAILY",
    statsActualizar = "UPDATE",
    statsMedicionDeHoy = "TODAY's MEASUREMENT",
    statsRegistraProgreso = "Log today's progress",
    statsYaRegistrasteHoy = "Already logged today — updating your existing measurement",
    statsRepetirUltima = "REPEAT LAST MEASUREMENT",
    statsPesoInput = "WEIGHT (kg)*",
    statsGrasaInput = "BODY FAT % (optional)",
    statsOcultarMedidas = "▲ HIDE DETAILED MEASUREMENTS",
    statsAnadirMedidas = "▼ ADD DETAILED MEASUREMENTS",
    statsMedidasMuscularesCm = "MUSCLE MEASUREMENTS (cm)",
    statsCancelar = "CANCEL",
    statsGuardar = "SAVE",

    // Chart Metrica
    statsMetricaPeso = "Weight",
    statsMetricaGrasa = "% Fat",
    statsMetricaMasaMagra = "Lean Mass",
    statsMetricaPecho = "Chest",
    statsMetricaEspalda = "Back",
    statsMetricaHombro = "Shoulder",
    statsMetricaBrazo = "Arm",
    statsMetricaMuslo = "Thigh",
    statsMetricaCintura = "Waist",

    // Auth Screens
    authWelcomeBack = "WELCOME BACK",
    authJoinElite = "JOIN THE ELITE",
    authSubtitle = "High-performance engineering\nfor your physical evolution.",
    authSignIn = "Sign In",
    authSignInDesc = "Enter your credentials to continue.",
    authCreateAccount = "Create Account",
    authCreateAccountDesc = "Enter your details to power up.",
    authEmail = "EMAIL ADDRESS",
    authPassword = "PASSWORD",
    authForgotPassword = "Forgot password?",
    authEnterArena = "ENTER THE ARENA",
    authNewToSquad = "New to the squad? ",
    authAlreadySquad = "Already part of the squad? ",
    authLogIn = "Log In",
    authCopyright = "© 2024 FIT-WIN PERFORMANCE TECHNOLOGIES",
    authName = "NAME",
    authSurname = "SURNAME",
    authWeight = "WEIGHT (KG)",
    authHeight = "HEIGHT (CM)",
    authDob = "DATE OF BIRTH (YYYY-MM-DD)",
    authGender = "GENDER",
    authActivityLevel = "ACTIVITY LEVEL",
    authObjective = "OBJECTIVE",
    authTerms = "I agree to the Terms of Service and Privacy Policy",
    authInitialize = "INITIALIZE TRAINING"
)
