package org.example.fitwinkmp.core.localization

val stringsEs = AppStrings(
    // Bottom nav
    navNutricion = "Nutrición",
    navEntreno = "Entreno",
    navStats = "Stats",
    navPerfil = "Perfil",

    // Food
    foodRegistroDiario = "REGISTRO DIARIO",
    foodHoy = "HOY",
    foodTitulo1 = "ALIMENTA TU",
    foodTitulo2 = "MOTOR",
    foodCaloriasRest = "CALORÍAS REST.",
    foodObjetivoKcal = "OBJETIVO:",
    foodProteinas = "PROTEÍNAS",
    foodCarbos = "CARBOS",
    foodGrasas = "GRASAS",
    foodDesayuno = "DESAYUNO",
    foodAlmuerzo = "ALMUERZO",
    foodCena = "CENA",
    foodSnacks = "SNACKS",
    foodRegistrado = "Registrado",
    foodTocaParaRegistrar = "TOCA PARA REGISTRAR",
    foodGuardar = "GUARDAR",
    foodCancelar = "CANCELAR",
    foodNombreAlimento = "Nombre del alimento",
    foodCantidad = "Cant.",
    foodUnidad = "Unidad",
    foodRegistrar = "REGISTRAR",
    foodEliminar = "Eliminar",
    foodEditar = "Editar",

    // Training
    trainingTitle = "ENTRENO",
    trainingPlanHoy = "PLAN DE HOY",
    trainingDiaDescanso = "DÍA DE DESCANSO O SIN RUTINA",
    trainingCrearRutina = "CREAR RUTINA",
    trainingSesionActiva = "SESIÓN ACTIVA",
    trainingAplastaReps = "¡A POR ELLO!",
    trainingObjetivo = "OBJETIVO:",
    trainingSerie = "SERIE",
    trainingTodasSeries = "TODAS LAS SERIES COMPLETADAS",
    trainingIniciarSesion = "INICIAR SESIÓN",
    trainingFinalizarSesion = "FINALIZAR SESIÓN",
    trainingNuevaRutina = "Nueva rutina",
    trainingEliminarRutina = "Eliminar rutina actual",
    trainingSeleccionarRutina = "Seleccionar rutina",
    trainingAnyadirEjercicio = "AÑADIR EJERCICIO",
    trainingNombreEjercicio = "Nombre del ejercicio",
    trainingEjemploEjercicio = "Ej. Press Banca, Sentadilla...",
    trainingSeries = "Series",
    trainingDescansoSeg = "Descanso (s)",
    trainingRepsMin = "Reps mín.",
    trainingRepsMax = "Reps máx.",
    trainingGuardarRutina = "GUARDAR RUTINA",
    trainingNombreRutina = "Nombre de la rutina",
    trainingSinEjercicios = "Sin ejercicios para este día",
    trainingAnadir = "AÑADIR",
    trainingCancelar = "CANCELAR",
    trainingDescanso = "DESCANSO",
    trainingRegistrar = "LOG",
    trainingEditarRutina = "Editar rutina",

    // Profile
    profilePesoActual = "PESO ACTUAL",
    profileAltura = "ALTURA",
    profileImc = "IMC",
    profileActividad = "ACTIVIDAD",
    profileObjetivoNutricional = "OBJETIVO NUTRICIONAL",
    profileMiCuenta = "MI CUENTA",
    profileEditarPerfil = "Editar perfil",
    profileInfoCuenta = "Información de la cuenta",
    profileCerrarSesion = "CERRAR SESIÓN",
    profileActualizado = "✓ Perfil actualizado",
    profileReintentar = "REINTENTAR",
    profileDesdeRegistro = "kg desde el registro",
    profileGenerarObjetivo = "Generar objetivo",

    // Edit profile dialog
    editPerfilTitulo1 = "EDITAR",
    editPerfilTitulo2 = "PERFIL",
    editPerfilCancelar = "CANCELAR",
    editPerfilDatosPersonales = "DATOS PERSONALES",
    editPerfilDatosFisicos = "DATOS FÍSICOS",
    editPerfilNombre = "Nombre",
    editPerfilApellidos = "Apellidos",
    editPerfilEmail = "Email",
    editPerfilPeso = "Peso (kg)",
    editPerfilAltura = "Altura (cm)",
    editPerfilGenero = "GÉNERO",
    editPerfilNivelActividad = "NIVEL DE ACTIVIDAD",
    editPerfilObjetivo = "OBJETIVO",
    editPerfilGuardar = "GUARDAR CAMBIOS",

    // Settings
    settingsTitulo = "AJUSTES",
    settingsIdioma = "IDIOMA",
    settingsEspanyol = "Español",
    settingsEspanyolSub = "Idioma actual de la aplicación",
    settingsIngles = "English",
    settingsInglesSub = "Application language",
    settingsInfoText = "Más opciones de configuración próximamente.",
    settingsVersion = "FIT-WIN v1.0.0",

    // Common
    commonProximamente = "PRÓXIMAMENTE",
    commonEstadisticas = "ESTADÍSTICAS",
    commonAjustes = "Ajustes",
    commonLoading = "Cargando..."
)
